# Documentation: http://docs.travis-ci.com/user/languages/julia
CODECOV_TOKEN='51315f14-4dea-48b6-b58f-fd37babbc990'
language: julia
codecov: true
notifications:
  email: msdale@uow.edu.au
julia:
  - 1.7
  - nightly
os:
  - linux
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
