# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
codecov: true
notifications:
  email: msdale@uow.edu.au
julia:
  - 1.7
  - nightly
os:
  - linux
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
env:
  - CODECOV_TOKEN='51315f14-4dea-48b6-b58f-fd37babbc990'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
  # - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("ReactiveBasics", "docs")); include("make.jl")'
  # push coverage results to Codecov:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
